Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JobScheduler.Data;
using JobScheduler.Models;
using Microsoft.AspNetCore.Authorization;
using JobScheduler.Infrastructure;
using JobScheduler.Abstract;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.AspNetCore.Authentication.JwtBearer;

namespace JobScheduler.Controllers
{
    [Authorize(Roles = Constants.ADMIN_ROLE + "," + Constants.EDITOR_ROLE)]
    public class JobsController : MvcCrudController<JobSchedulerContext, Job>
    {
        private readonly JobSchedulerContext _context;
        private readonly IConfiguration _configuration;

        public JobsController(JobSchedulerContext context, IConfiguration configuration, IServiceScopeFactory _scopeFactory)
            : base(context, _scopeFactory, configuration)
        {
            _context = context;
            _configuration = configuration;
        }

        public async Task<IActionResult> Launch(LaunchJob launchJob)
        {

            DbContextUtility dbContextUtility = new DbContextUtility(_context, _configuration);
            await dbContextUtility.Launch(launchJob);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Stop(StopJob stopJob)
        {
            if (stopJob.JobId == 0 )
            {
                //Gestirla con una schermata di errore ad hoc
                return RedirectToAction(nameof(Index));
            }

            DbContextUtility dbContextUtility = new DbContextUtility(_context, _configuration);
            await dbContextUtility.Stop(stopJob);
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using JobScheduler.Data;
using JobScheduler.Infrastructure;
using JobScheduler.Models;
using JobScheduler.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication.JwtBearer;

namespace JobScheduler.Controllers
{
    [Authorize(Roles = Constants.ADMIN_ROLE)]
    public class RoleController : Controller
    {
        private readonly RolesUtility _roleUtility;
        public RoleController(RoleManager<IdentityRole> roleManager, JobSchedulerContext context)
        {
            _roleUtility = new RolesUtility(roleManager, context);
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(_roleUtility.GetRoles());
        }

        public async Task<IActionResult> Details(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
            {
                return NotFound();
            }
            var role = await _roleUtility.GetRoleById(id);

            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            if (ModelState.IsValid)
            {
                string errorResult = await _roleUtility.Create(role);

                if (string.IsNullOrWhiteSpace(errorResult))
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Create");
        }

        public async Task<IActionResult> Edit(string id)
        {
            IdentityRole user = await _roleUtility.GetRoleById(id);

            if (user != null)
                return View(user);
            else
                return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(IdentityRole role)
        {
            if (role == null)
            {
                return NotFound();
            }

            var result = await _roleUtility.Update(role);
            if (result == null || result.Succeeded == false)
            {
                return View(role);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JobScheduler</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">JobScheduler</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>

                            @if (User.IsInRole(JobScheduler.Infrastructure.Constants.ADMIN_ROLE))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                                        Admin
                                    </a>
                                    <div class="dropdown-menu">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="UserRole" asp-action="Index">UsersRoles</a>
                                    </div>
                                </li>

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                                        Jobs
                                    </a>
                                    <div class="dropdown-menu">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Jobs" asp-action="Index">Jobs</a>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Nodes" asp-action="Index">Nodes</a>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Groups" asp-action="Index">Groups</a>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="GroupNodes" asp-action="Index">GroupNodes</a>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="JobGroups" asp-action="Index">JobGroups</a>
                                    </div>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                                        Jobs
                                    </a>
                                    <div class="dropdown-menu">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Jobs" asp-action="Index">Jobs</a>
                                    </div>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="NodeLaunchResult" asp-action="Index">Execution logs</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout [@User.Identity.Name]</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>